# Generated by Django 3.1.7 on 2021-11-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('Rent', 'Rent'), ('Garbage', 'Garbage'), ('Internet', 'Internet'), ('Damages', 'Damages'), ('Deposit', 'Deposit')], max_length=20)),
                ('posted_by', models.CharField(max_length=30)),
                ('Description', models.CharField(choices=[('Cash', 'Cash'), ('Credit_Card', 'Credit_Card'), ('Bank', 'Bank'), ('Mpesa', 'Mpesa')], max_length=20)),
                ('amount', models.CharField(max_length=30)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
    ]
