# Generated by Django 3.1.7 on 2021-12-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_auto_20211202_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charges',
            old_name='Customer',
            new_name='customer',
        ),
    ]
