# Generated by Django 3.1.7 on 2021-12-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0004_auto_20211205_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charges',
            old_name='tenant',
            new_name='user_name',
        ),
    ]
