# Generated by Django 3.1.7 on 2021-12-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='unit',
            field=models.CharField(default='4A', max_length=30),
            preserve_default=False,
        ),
    ]
