# Generated by Django 3.1.7 on 2021-12-05 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenant', '0002_tenant_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='unit',
        ),
        migrations.AddField(
            model_name='tenant',
            name='unit_id',
            field=models.ForeignKey(default='5B', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
            preserve_default=False,
        ),
    ]
