# Generated by Django 3.1.7 on 2021-11-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('property_name', models.CharField(max_length=30)),
                ('category_name', models.CharField(choices=[('BS', 'Bedsitter'), ('1B', '1-Bedroom'), ('2B', '2-Bedroom'), ('OS', 'Office')], default='BS', max_length=2)),
                ('unit_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('costing', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('is_inactive', models.CharField(max_length=30)),
            ],
        ),
    ]
