# Generated by Django 3.1.7 on 2021-09-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('property_name', models.CharField(max_length=30, verbose_name='the property name')),
                ('category_name', models.CharField(max_length=30, verbose_name='category of property')),
                ('unit_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='unit identifier')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('costing', models.CharField(max_length=30, verbose_name='cost of unit')),
                ('price', models.CharField(max_length=30, verbose_name='renting/selling/leasing price')),
                ('is_inactive', models.CharField(max_length=30, verbose_name='property availability')),
            ],
        ),
    ]
