# Generated by Django 3.1.7 on 2021-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='costing',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='is_inactive',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='property_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
